version: "3"

services:
  db:
    image: driven-distances/db
    build: 
      context: ./
      dockerfile: ./.docker/db/Dockerfile
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
      - ./.docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  job:
    image: driven-distances/job
    build: 
      context: ./
      dockerfile: ./.docker/job/Dockerfile
    command: -f /workdir/input/bern.csv -o /workdir/output/bern.csv -l mysql
    env_file:
      - ./.env
    links:
      - "db"
    volumes:
      - ./output:/workdir/output
      - ./input:/workdir/input
  
  service:
    image: driven-distances/service
    build: 
      context: ./
      dockerfile: ./.docker/service/Dockerfile
    env_file:
      - ./.env
    links:
      - "db"
    volumes:
      - ./api:/workdir
    ports:
      - 32193:5000

  server:
    image: nginx:1.17
    ports:
      - 8000:80
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
    links:
      - "service"

volumes:
  db-data: